DROP DATABASE IF EXISTS polygon;
CREATE DATABASE polygon;
USE polygon;
DROP TABLE IF EXISTS login;
DROP TABLE IF EXISTS firm;
DROP TABLE IF EXISTS Zip;
DROP TABLE IF EXISTS buildings;
DROP TABLE IF EXISTS building_floors;
DROP TABLE IF EXISTS images;
DROP TABLE IF EXISTS building_report;
DROP TABLE IF EXISTS building_room;

CREATE TABLE login(
username VARCHAR(10) UNIQUE,
password VARCHAR(10),
user_id INT(10) AUTO_INCREMENT,
user_role VARCHAR(10),
user_firm VARCHAR (10),
primary key (user_id)
);

CREATE TABLE Zip(
zipcode INT(10),
city VARCHAR(45),
primary key (zipcode)
);

CREATE TABLE firm(
firm_name VARCHAR(10) UNIQUE,
firm_leader_id INT(10),
firm_id INT(10) NOT NULL AUTO_INCREMENT,
PRIMARY key (firm_id),
FOREIGN KEY (firm_leader_id) 
REFERENCES login(user_id)
);

CREATE TABLE buildings(
building_id INT(10) NOT NULL AUTO_INCREMENT,
building_name VARCHAR(45),
building_status VARCHAR(145),
building_type VARCHAR(145),
building_adress VARCHAR(45),
building_year INT(10),
building_zipcode INT(10),
building_areasize INT(10),
building_parcel_no VARCHAR(10),
building_floor VARCHAR(10),
building_firm_id INT(10),
primary key (building_id),
FOREIGN KEY (building_zipcode) 
REFERENCES Zip(zipcode),
FOREIGN KEY (building_firm_id) 
REFERENCES firm(firm_id)
);

CREATE TABLE building_floors(
floor_building_id int(10),
floor_no INT(10),
floor_size int(10),
floor_arpartments VARCHAR(20),
floor_rooms VARCHAR(20),
FOREIGN KEY (floor_building_id) 
REFERENCES Buildings(building_id)
);

CREATE TABLE images(
image_id INT(10) not null auto_increment,
image_name VARCHAR(10) not null,
Photo mediumblob,
primary key (image_id)
);

CREATE TABLE building_report(
report_id INT (10),
report_outer_roof VARCHAR (20),
/*report_outer_roof_pic MEDIUMBLOB,*/
report_outer_wall VARCHAR (20),
/*report_outer_wall_pic MEDIUMBLOB,*/
report_building_usage VARCHAR (20),
/*report_report_filler VARCHAR (20),*/
report_building_manager VARCHAR (20),
report_building_condetion INT (10),
FOREIGN KEY (report_building_condetion) 
REFERENCES buildings(building_id)
);


CREATE TABLE building_room(
room_apartment_id INT (10),
room_size INT (10),
room_usages VARCHAR (20),
room_overall_any_comments VARCHAR (10),
room_any_damage VARCHAR (20),
room_date_of_damage DATE,
room_place_of_damage VARCHAR (20),
room_damage_happend VARCHAR (20),
room_damage_replaced VARCHAR (20),
room_the_damage VARCHAR (20),
/*All dem som hedder noget med comment er ja/nej og derefter er det bemærkningens felt og så billede */
room_comment_inner_wall VARCHAR(10),
room_inner_wall VARCHAR(20),
room_inner_wall_pic mediumblob,
room_comment_inner_roof VARCHAR (10),
room_inner_roof VARCHAR (20),
room_inner_roof_pic mediumblob,
room_comment_inner_floor VARCHAR (10),
room_inner_floor VARCHAR (20),
room_inner_floor_pic mediumblob,
room_comment_window VARCHAR (10),
room_window VARCHAR (20),
room_window_pic mediumblob,
room_comment_door VARCHAR(10),
room_door VARCHAR (20),
room_door_pic mediumblob,
/*m = moisture s = scanning */
room_m_s VARCHAR (10),
room_m_s_date DATE,
room_m_s_measurin_point INT (20),
room_recommendations VARCHAR (30)
);



INSERT INTO Zip VALUES ('0800', 'H¯je Taastrup');
INSERT INTO Zip VALUES ('0877', 'Valby');
INSERT INTO Zip VALUES ('0900', 'K¯benhavn C');
INSERT INTO Zip VALUES ('0910', 'K¯benhavn C');
INSERT INTO Zip VALUES ('0929', 'K¯benhavn C');
INSERT INTO Zip VALUES ('1000', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1001', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1002', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1003', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1004', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1005', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1006', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1007', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1008', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1009', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1010', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1011', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1012', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1013', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1014', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1015', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1016', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1017', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1018', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1019', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1020', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1021', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1022', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1023', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1024', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1025', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1026', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1045', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1050', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1051', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1052', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1053', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1054', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1055', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1056', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1057', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1058', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1059', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1060', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1061', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1062', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1063', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1064', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1065', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1066', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1067', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1068', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1069', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1070', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1071', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1072', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1073', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1074', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1092', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1093', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1095', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1098', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1100', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1101', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1102', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1103', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1104', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1105', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1106', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1107', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1110', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1111', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1112', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1113', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1114', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1115', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1116', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1117', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1118', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1119', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1120', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1121', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1122', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1123', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1124', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1125', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1126', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1127', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1128', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1129', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1130', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1131', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1140', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1147', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1148', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1150', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1151', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1152', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1153', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1154', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1155', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1156', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1157', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1158', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1159', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1160', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1161', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1162', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1163', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1164', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1165', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1166', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1167', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1168', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1169', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1170', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1171', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1172', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1173', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1174', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1175', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1200', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1201', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1202', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1203', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1204', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1205', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1206', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1207', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1208', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1209', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1210', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1211', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1212', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1213', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1214', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1215', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1216', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1217', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1218', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1219', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1220', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1240', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1250', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1251', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1252', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1253', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1254', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1255', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1256', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1257', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1258', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1259', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1260', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1261', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1263', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1264', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1265', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1266', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1267', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1268', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1270', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1271', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1291', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1300', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1301', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1302', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1303', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1304', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1306', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1307', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1308', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1309', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1310', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1311', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1312', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1313', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1314', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1315', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1316', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1317', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1318', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1319', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1320', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1321', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1322', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1323', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1324', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1325', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1326', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1327', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1328', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1329', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1349', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1350', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1352', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1353', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1354', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1355', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1356', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1357', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1358', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1359', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1360', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1361', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1362', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1363', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1364', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1365', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1366', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1367', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1368', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1369', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1370', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1371', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1390', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1399', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1400', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1401', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1402', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1403', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1404', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1405', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1406', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1407', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1408', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1409', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1410', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1411', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1412', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1413', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1414', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1415', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1416', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1417', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1418', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1419', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1420', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1421', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1422', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1423', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1424', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1425', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1426', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1427', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1428', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1429', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1430', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1431', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1432', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1433', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1434', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1435', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1436', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1437', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1438', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1439', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1440', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1441', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1448', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1450', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1451', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1452', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1453', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1454', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1455', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1456', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1457', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1458', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1459', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1460', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1461', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1462', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1463', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1464', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1465', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1466', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1467', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1468', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1470', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1471', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1472', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1473', 'K¯benhavn K');
INSERT INTO Zip VALUES ('1500', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1501', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1502', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1503', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1504', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1505', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1506', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1507', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1508', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1509', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1510', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1532', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1533', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1550', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1551', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1552', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1553', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1554', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1555', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1556', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1557', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1558', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1559', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1560', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1561', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1562', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1563', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1564', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1566', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1567', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1568', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1569', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1570', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1571', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1572', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1573', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1574', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1575', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1576', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1577', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1590', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1592', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1595', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1599', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1600', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1601', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1602', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1603', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1604', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1605', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1606', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1607', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1608', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1609', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1610', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1611', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1612', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1613', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1614', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1615', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1616', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1617', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1618', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1619', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1620', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1621', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1622', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1623', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1624', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1630', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1631', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1632', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1633', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1634', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1635', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1639', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1640', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1650', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1651', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1652', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1653', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1654', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1655', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1656', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1657', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1658', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1659', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1660', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1661', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1662', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1663', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1664', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1665', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1666', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1667', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1668', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1669', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1670', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1671', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1672', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1673', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1674', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1675', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1676', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1677', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1699', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1700', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1701', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1702', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1703', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1704', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1705', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1706', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1707', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1708', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1709', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1710', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1711', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1712', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1713', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1714', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1715', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1716', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1717', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1718', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1719', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1720', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1721', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1722', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1723', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1724', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1725', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1726', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1727', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1728', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1729', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1730', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1731', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1732', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1733', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1734', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1735', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1736', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1737', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1738', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1739', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1748', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1749', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1750', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1751', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1752', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1753', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1754', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1755', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1756', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1757', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1758', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1759', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1760', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1761', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1762', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1763', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1764', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1765', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1766', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1770', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1771', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1772', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1773', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1774', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1775', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1777', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1778', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1780', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1782', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1783', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1784', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1785', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1786', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1787', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1788', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1789', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1790', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1795', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1799', 'K¯benhavn V');
INSERT INTO Zip VALUES ('1800', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1801', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1802', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1803', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1804', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1805', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1806', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1807', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1808', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1809', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1810', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1811', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1812', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1813', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1814', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1815', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1816', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1817', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1818', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1819', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1820', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1822', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1823', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1824', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1825', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1826', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1827', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1828', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1829', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1835', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1850', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1851', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1852', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1853', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1854', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1855', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1856', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1857', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1860', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1861', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1862', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1863', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1864', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1865', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1866', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1867', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1868', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1870', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1871', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1872', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1873', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1874', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1875', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1876', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1877', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1878', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1879', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1900', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1901', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1902', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1903', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1904', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1905', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1906', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1908', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1909', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1910', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1911', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1912', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1913', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1914', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1915', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1916', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1917', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1920', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1921', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1922', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1923', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1924', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1925', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1926', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1927', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1928', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1931', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1950', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1951', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1952', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1953', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1954', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1955', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1956', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1957', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1958', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1959', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1960', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1961', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1962', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1963', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1964', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1965', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1966', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1967', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1970', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1971', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1972', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1973', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1974', 'Frederiksberg C');
INSERT INTO Zip VALUES ('1999', 'Frederiksberg C');
INSERT INTO Zip VALUES ('2000', 'Frederiksberg');
INSERT INTO Zip VALUES ('2100', 'K¯benhavn ÿ');
INSERT INTO Zip VALUES ('2200', 'K¯benhavn N');
INSERT INTO Zip VALUES ('2300', 'K¯benhavn S');
INSERT INTO Zip VALUES ('2400', 'K¯benhavn NV');
INSERT INTO Zip VALUES ('2450', 'K¯benhavn SV');
INSERT INTO Zip VALUES ('2500', 'Valby');
INSERT INTO Zip VALUES ('2600', 'Glostrup');
INSERT INTO Zip VALUES ('2605', 'Br¯ndby');
INSERT INTO Zip VALUES ('2610', 'R¯dovre');
INSERT INTO Zip VALUES ('2620', 'Albertslund');
INSERT INTO Zip VALUES ('2625', 'VallensbÊk');
INSERT INTO Zip VALUES ('2630', 'Taastrup');
INSERT INTO Zip VALUES ('2633', 'Taastrup');
INSERT INTO Zip VALUES ('2635', 'Ish¯j');
INSERT INTO Zip VALUES ('2640', 'Hedehusene');
INSERT INTO Zip VALUES ('2650', 'Hvidovre');
INSERT INTO Zip VALUES ('2660', 'Br¯ndby Strand');
INSERT INTO Zip VALUES ('2665', 'VallensbÊk Strand');
INSERT INTO Zip VALUES ('2670', 'Greve');
INSERT INTO Zip VALUES ('2680', 'Solr¯d Strand');
INSERT INTO Zip VALUES ('2690', 'Karlslunde');
INSERT INTO Zip VALUES ('2700', 'Br¯nsh¯j');
INSERT INTO Zip VALUES ('2720', 'Vanl¯se');
INSERT INTO Zip VALUES ('2730', 'Herlev');
INSERT INTO Zip VALUES ('2740', 'Skovlunde');
INSERT INTO Zip VALUES ('2750', 'Ballerup');
INSERT INTO Zip VALUES ('2760', 'MÂl¯v');
INSERT INTO Zip VALUES ('2765', 'Sm¯rum');
INSERT INTO Zip VALUES ('2770', 'Kastrup');
INSERT INTO Zip VALUES ('2791', 'Drag¯r');
INSERT INTO Zip VALUES ('2800', 'Kongens Lyngby');
INSERT INTO Zip VALUES ('2820', 'Gentofte');
INSERT INTO Zip VALUES ('2830', 'Virum');
INSERT INTO Zip VALUES ('2840', 'Holte');
INSERT INTO Zip VALUES ('2850', 'NÊrum');
INSERT INTO Zip VALUES ('2860', 'S¯borg');
INSERT INTO Zip VALUES ('2870', 'DyssegÂrd');
INSERT INTO Zip VALUES ('2880', 'BagsvÊrd');
INSERT INTO Zip VALUES ('2900', 'Hellerup');
INSERT INTO Zip VALUES ('2920', 'Charlottenlund');
INSERT INTO Zip VALUES ('2930', 'Klampenborg');
INSERT INTO Zip VALUES ('2942', 'Skodsborg');
INSERT INTO Zip VALUES ('2950', 'VedbÊk');
INSERT INTO Zip VALUES ('2960', 'Rungsted Kyst');
INSERT INTO Zip VALUES ('2970', 'H¯rsholm');
INSERT INTO Zip VALUES ('2980', 'Kokkedal');
INSERT INTO Zip VALUES ('2990', 'NivÂ');
INSERT INTO Zip VALUES ('3000', 'Helsing¯r');
INSERT INTO Zip VALUES ('3050', 'HumlebÊk');
INSERT INTO Zip VALUES ('3060', 'EspergÊrde');
INSERT INTO Zip VALUES ('3070', 'Snekkersten');
INSERT INTO Zip VALUES ('3080', 'Tik¯b');
INSERT INTO Zip VALUES ('3100', 'HornbÊk');
INSERT INTO Zip VALUES ('3120', 'Dronningm¯lle');
INSERT INTO Zip VALUES ('3140', '≈lsgÂrde');
INSERT INTO Zip VALUES ('3150', 'HellebÊk');
INSERT INTO Zip VALUES ('3200', 'Helsinge');
INSERT INTO Zip VALUES ('3210', 'Vejby');
INSERT INTO Zip VALUES ('3220', 'Tisvildeleje');
INSERT INTO Zip VALUES ('3230', 'GrÊsted');
INSERT INTO Zip VALUES ('3250', 'Gilleleje');
INSERT INTO Zip VALUES ('3300', 'FrederiksvÊrk');
INSERT INTO Zip VALUES ('3310', 'ÿlsted');
INSERT INTO Zip VALUES ('3320', 'SkÊvinge');
INSERT INTO Zip VALUES ('3330', 'G¯rl¯se');
INSERT INTO Zip VALUES ('3360', 'Liseleje');
INSERT INTO Zip VALUES ('3370', 'Melby');
INSERT INTO Zip VALUES ('3390', 'Hundested');
INSERT INTO Zip VALUES ('3400', 'Hiller¯d');
INSERT INTO Zip VALUES ('3450', 'Aller¯d');
INSERT INTO Zip VALUES ('3460', 'Birker¯d');
INSERT INTO Zip VALUES ('3480', 'Fredensborg');
INSERT INTO Zip VALUES ('3490', 'KvistgÂrd');
INSERT INTO Zip VALUES ('3500', 'VÊrl¯se');
INSERT INTO Zip VALUES ('3520', 'Farum');
INSERT INTO Zip VALUES ('3540', 'Lynge');
INSERT INTO Zip VALUES ('3550', 'Slangerup');
INSERT INTO Zip VALUES ('3600', 'Frederikssund');
INSERT INTO Zip VALUES ('3630', 'JÊgerspris');
INSERT INTO Zip VALUES ('3650', 'ÿlstykke');
INSERT INTO Zip VALUES ('3660', 'Stenl¯se');
INSERT INTO Zip VALUES ('3670', 'Veks¯ SjÊlland');
INSERT INTO Zip VALUES ('3700', 'R¯nne');
INSERT INTO Zip VALUES ('3720', 'Aakirkeby');
INSERT INTO Zip VALUES ('3730', 'Nex¯');
INSERT INTO Zip VALUES ('3740', 'Svaneke');
INSERT INTO Zip VALUES ('3751', 'ÿstermarie');
INSERT INTO Zip VALUES ('3760', 'Gudhjem');
INSERT INTO Zip VALUES ('3770', 'Allinge');
INSERT INTO Zip VALUES ('3782', 'Klemensker');
INSERT INTO Zip VALUES ('3790', 'Hasle');
INSERT INTO Zip VALUES ('4000', 'Roskilde');
INSERT INTO Zip VALUES ('4030', 'Tune');
INSERT INTO Zip VALUES ('4040', 'Jyllinge');
INSERT INTO Zip VALUES ('4050', 'Skibby');
INSERT INTO Zip VALUES ('4060', 'Kirke SÂby');
INSERT INTO Zip VALUES ('4070', 'Kirke Hyllinge');
INSERT INTO Zip VALUES ('4100', 'Ringsted');
INSERT INTO Zip VALUES ('4105', 'Ringsted');
INSERT INTO Zip VALUES ('4129', 'Ringsted');
INSERT INTO Zip VALUES ('4130', 'Viby SjÊlland');
INSERT INTO Zip VALUES ('4140', 'Borup');
INSERT INTO Zip VALUES ('4160', 'Herlufmagle');
INSERT INTO Zip VALUES ('4171', 'Glums¯');
INSERT INTO Zip VALUES ('4173', 'Fjenneslev');
INSERT INTO Zip VALUES ('4174', 'Jystrup Midtsj');
INSERT INTO Zip VALUES ('4180', 'Sor¯');
INSERT INTO Zip VALUES ('4190', 'Munke Bjergby');
INSERT INTO Zip VALUES ('4200', 'Slagelse');
INSERT INTO Zip VALUES ('4220', 'Kors¯r');
INSERT INTO Zip VALUES ('4230', 'SkÊlsk¯r');
INSERT INTO Zip VALUES ('4241', 'Vemmelev');
INSERT INTO Zip VALUES ('4242', 'Boeslunde');
INSERT INTO Zip VALUES ('4243', 'Rude');
INSERT INTO Zip VALUES ('4250', 'Fuglebjerg');
INSERT INTO Zip VALUES ('4261', 'Dalmose');
INSERT INTO Zip VALUES ('4262', 'Sandved');
INSERT INTO Zip VALUES ('4270', 'H¯ng');
INSERT INTO Zip VALUES ('4281', 'G¯rlev');
INSERT INTO Zip VALUES ('4291', 'Ruds Vedby');
INSERT INTO Zip VALUES ('4293', 'Dianalund');
INSERT INTO Zip VALUES ('4295', 'Stenlille');
INSERT INTO Zip VALUES ('4296', 'Nyrup');
INSERT INTO Zip VALUES ('4300', 'HolbÊk');
INSERT INTO Zip VALUES ('4320', 'Lejre');
INSERT INTO Zip VALUES ('4330', 'Hvals¯');
INSERT INTO Zip VALUES ('4340', 'T¯ll¯se');
INSERT INTO Zip VALUES ('4350', 'Ugerl¯se');
INSERT INTO Zip VALUES ('4360', 'Kirke Eskilstrup');
INSERT INTO Zip VALUES ('4370', 'Store Merl¯se');
INSERT INTO Zip VALUES ('4390', 'Vipper¯d');
INSERT INTO Zip VALUES ('4400', 'Kalundborg');
INSERT INTO Zip VALUES ('4420', 'Regstrup');
INSERT INTO Zip VALUES ('4440', 'M¯rk¯v');
INSERT INTO Zip VALUES ('4450', 'Jyderup');
INSERT INTO Zip VALUES ('4460', 'Snertinge');
INSERT INTO Zip VALUES ('4470', 'Sveb¯lle');
INSERT INTO Zip VALUES ('4480', 'Store Fuglede');
INSERT INTO Zip VALUES ('4490', 'Jerslev SjÊlland');
INSERT INTO Zip VALUES ('4500', 'Nyk¯bing Sj');
INSERT INTO Zip VALUES ('4520', 'Svinninge');
INSERT INTO Zip VALUES ('4532', 'Gislinge');
INSERT INTO Zip VALUES ('4534', 'H¯rve');
INSERT INTO Zip VALUES ('4540', 'FÂrevejle');
INSERT INTO Zip VALUES ('4550', 'AsnÊs');
INSERT INTO Zip VALUES ('4560', 'Vig');
INSERT INTO Zip VALUES ('4571', 'Grevinge');
INSERT INTO Zip VALUES ('4572', 'N¯rre Asmindrup');
INSERT INTO Zip VALUES ('4573', 'H¯jby');
INSERT INTO Zip VALUES ('4581', 'R¯rvig');
INSERT INTO Zip VALUES ('4583', 'SjÊllands Odde');
INSERT INTO Zip VALUES ('4591', 'F¯llenslev');
INSERT INTO Zip VALUES ('4592', 'Sejer¯');
INSERT INTO Zip VALUES ('4593', 'Eskebjerg');
INSERT INTO Zip VALUES ('4600', 'K¯ge');
INSERT INTO Zip VALUES ('4621', 'Gadstrup');
INSERT INTO Zip VALUES ('4622', 'Havdrup');
INSERT INTO Zip VALUES ('4623', 'Lille Skensved');
INSERT INTO Zip VALUES ('4632', 'BjÊverskov');
INSERT INTO Zip VALUES ('4640', 'Fakse');
INSERT INTO Zip VALUES ('4652', 'HÂrlev');
INSERT INTO Zip VALUES ('4653', 'Karise');
INSERT INTO Zip VALUES ('4654', 'Fakse Ladeplads');
INSERT INTO Zip VALUES ('4660', 'Store Heddinge');
INSERT INTO Zip VALUES ('4671', 'Str¯by');
INSERT INTO Zip VALUES ('4672', 'Klippinge');
INSERT INTO Zip VALUES ('4673', 'R¯dvig Stevns');
INSERT INTO Zip VALUES ('4681', 'Herf¯lge');
INSERT INTO Zip VALUES ('4682', 'Tureby');
INSERT INTO Zip VALUES ('4683', 'R¯nnede');
INSERT INTO Zip VALUES ('4684', 'Holmegaard');
INSERT INTO Zip VALUES ('4690', 'Haslev');
INSERT INTO Zip VALUES ('4700', 'NÊstved');
INSERT INTO Zip VALUES ('4720', 'PrÊst¯');
INSERT INTO Zip VALUES ('4733', 'Tappern¯je');
INSERT INTO Zip VALUES ('4735', 'Mern');
INSERT INTO Zip VALUES ('4736', 'KarrebÊksminde');
INSERT INTO Zip VALUES ('4750', 'Lundby');
INSERT INTO Zip VALUES ('4760', 'Vordingborg');
INSERT INTO Zip VALUES ('4771', 'Kalvehave');
INSERT INTO Zip VALUES ('4772', 'LangebÊk');
INSERT INTO Zip VALUES ('4773', 'Stensved');
INSERT INTO Zip VALUES ('4780', 'Stege');
INSERT INTO Zip VALUES ('4791', 'Borre');
INSERT INTO Zip VALUES ('4792', 'Askeby');
INSERT INTO Zip VALUES ('4793', 'Bog¯ By');
INSERT INTO Zip VALUES ('4800', 'Nyk¯bing F');
INSERT INTO Zip VALUES ('4840', 'N¯rre Alslev');
INSERT INTO Zip VALUES ('4850', 'Stubbek¯bing');
INSERT INTO Zip VALUES ('4862', 'Guldborg');
INSERT INTO Zip VALUES ('4863', 'Eskilstrup');
INSERT INTO Zip VALUES ('4871', 'Horbelev');
INSERT INTO Zip VALUES ('4872', 'Idestrup');
INSERT INTO Zip VALUES ('4873', 'VÊggerl¯se');
INSERT INTO Zip VALUES ('4874', 'Gedser');
INSERT INTO Zip VALUES ('4880', 'Nysted');
INSERT INTO Zip VALUES ('4891', 'Toreby L');
INSERT INTO Zip VALUES ('4892', 'Kettinge');
INSERT INTO Zip VALUES ('4894', 'ÿster Ulslev');
INSERT INTO Zip VALUES ('4895', 'Errindlev');
INSERT INTO Zip VALUES ('4900', 'Nakskov');
INSERT INTO Zip VALUES ('4912', 'Harpelunde');
INSERT INTO Zip VALUES ('4913', 'Horslunde');
INSERT INTO Zip VALUES ('4920', 'S¯llested');
INSERT INTO Zip VALUES ('4930', 'Maribo');
INSERT INTO Zip VALUES ('4941', 'Bandholm');
INSERT INTO Zip VALUES ('4943', 'Torrig L');
INSERT INTO Zip VALUES ('4944', 'Fej¯');
INSERT INTO Zip VALUES ('4951', 'N¯rreballe');
INSERT INTO Zip VALUES ('4952', 'Stokkemarke');
INSERT INTO Zip VALUES ('4953', 'Vesterborg');
INSERT INTO Zip VALUES ('4960', 'Holeby');
INSERT INTO Zip VALUES ('4970', 'R¯dby');
INSERT INTO Zip VALUES ('4983', 'Dannemare');
INSERT INTO Zip VALUES ('4990', 'Saksk¯bing');
INSERT INTO Zip VALUES ('5000', 'Odense C');
INSERT INTO Zip VALUES ('5029', 'Odense C');
INSERT INTO Zip VALUES ('5090', 'Odense C');
INSERT INTO Zip VALUES ('5100', 'Odense C');
INSERT INTO Zip VALUES ('5200', 'Odense V');
INSERT INTO Zip VALUES ('5210', 'Odense NV');
INSERT INTO Zip VALUES ('5220', 'Odense Sÿ');
INSERT INTO Zip VALUES ('5230', 'Odense M');
INSERT INTO Zip VALUES ('5240', 'Odense Nÿ');
INSERT INTO Zip VALUES ('5250', 'Odense SV');
INSERT INTO Zip VALUES ('5260', 'Odense S');
INSERT INTO Zip VALUES ('5270', 'Odense N');
INSERT INTO Zip VALUES ('5290', 'Marslev');
INSERT INTO Zip VALUES ('5300', 'Kerteminde');
INSERT INTO Zip VALUES ('5320', 'Agedrup');
INSERT INTO Zip VALUES ('5330', 'Munkebo');
INSERT INTO Zip VALUES ('5350', 'Rynkeby');
INSERT INTO Zip VALUES ('5370', 'Mesinge');
INSERT INTO Zip VALUES ('5380', 'Dalby');
INSERT INTO Zip VALUES ('5390', 'Martofte');
INSERT INTO Zip VALUES ('5400', 'Bogense');
INSERT INTO Zip VALUES ('5450', 'Otterup');
INSERT INTO Zip VALUES ('5462', 'Morud');
INSERT INTO Zip VALUES ('5463', 'Harndrup');
INSERT INTO Zip VALUES ('5464', 'Brenderup Fyn');
INSERT INTO Zip VALUES ('5466', 'Asperup');
INSERT INTO Zip VALUES ('5471', 'S¯nders¯');
INSERT INTO Zip VALUES ('5474', 'Veflinge');
INSERT INTO Zip VALUES ('5485', 'Skamby');
INSERT INTO Zip VALUES ('5491', 'Blommenslyst');
INSERT INTO Zip VALUES ('5492', 'Vissenbjerg');
INSERT INTO Zip VALUES ('5500', 'Middelfart');
INSERT INTO Zip VALUES ('5540', 'Ullerslev');
INSERT INTO Zip VALUES ('5550', 'Langeskov');
INSERT INTO Zip VALUES ('5560', 'Aarup');
INSERT INTO Zip VALUES ('5580', 'N¯rre Aaby');
INSERT INTO Zip VALUES ('5591', 'Gelsted');
INSERT INTO Zip VALUES ('5592', 'Ejby');
INSERT INTO Zip VALUES ('5600', 'Faaborg');
INSERT INTO Zip VALUES ('5610', 'Assens');
INSERT INTO Zip VALUES ('5620', 'Glamsbjerg');
INSERT INTO Zip VALUES ('5631', 'Ebberup');
INSERT INTO Zip VALUES ('5642', 'Millinge');
INSERT INTO Zip VALUES ('5672', 'Broby');
INSERT INTO Zip VALUES ('5683', 'Haarby');
INSERT INTO Zip VALUES ('5690', 'Tommerup');
INSERT INTO Zip VALUES ('5700', 'Svendborg');
INSERT INTO Zip VALUES ('5750', 'Ringe');
INSERT INTO Zip VALUES ('5762', 'Vester Skerninge');
INSERT INTO Zip VALUES ('5771', 'Stenstrup');
INSERT INTO Zip VALUES ('5772', 'KvÊrndrup');
INSERT INTO Zip VALUES ('5792', '≈rslev');
INSERT INTO Zip VALUES ('5800', 'Nyborg');
INSERT INTO Zip VALUES ('5853', 'ÿrbÊk');
INSERT INTO Zip VALUES ('5854', 'Gislev');
INSERT INTO Zip VALUES ('5856', 'Ryslinge');
INSERT INTO Zip VALUES ('5863', 'Ferritslev Fyn');
INSERT INTO Zip VALUES ('5871', 'Fr¯rup');
INSERT INTO Zip VALUES ('5874', 'Hesselager');
INSERT INTO Zip VALUES ('5881', 'SkÂrup Fyn');
INSERT INTO Zip VALUES ('5882', 'Vejstrup');
INSERT INTO Zip VALUES ('5883', 'Oure');
INSERT INTO Zip VALUES ('5884', 'Gudme');
INSERT INTO Zip VALUES ('5892', 'Gudbjerg Sydfyn');
INSERT INTO Zip VALUES ('5900', 'Ru¯bing');
INSERT INTO Zip VALUES ('5932', 'Humble');
INSERT INTO Zip VALUES ('5935', 'Bagenkop');
INSERT INTO Zip VALUES ('5953', 'TranekÊr');
INSERT INTO Zip VALUES ('5960', 'Marstal');
INSERT INTO Zip VALUES ('5970', '∆r¯sk¯bing');
INSERT INTO Zip VALUES ('5985', 'S¯by ∆r¯');
INSERT INTO Zip VALUES ('6000', 'Kolding');
INSERT INTO Zip VALUES ('6040', 'Egtved');
INSERT INTO Zip VALUES ('6051', 'Almind');
INSERT INTO Zip VALUES ('6052', 'Viuf');
INSERT INTO Zip VALUES ('6064', 'Jordrup');
INSERT INTO Zip VALUES ('6070', 'Christiansfeld');
INSERT INTO Zip VALUES ('6091', 'Bjert');
INSERT INTO Zip VALUES ('6092', 'S¯nder Stenderup');
INSERT INTO Zip VALUES ('6093', 'Sj¯lund');
INSERT INTO Zip VALUES ('6094', 'Hejls');
INSERT INTO Zip VALUES ('6100', 'Haderslev');
INSERT INTO Zip VALUES ('6200', 'Aabenraa');
INSERT INTO Zip VALUES ('6230', 'R¯dekro');
INSERT INTO Zip VALUES ('6240', 'L¯gumkloster');
INSERT INTO Zip VALUES ('6261', 'Bredebro');
INSERT INTO Zip VALUES ('6270', 'T¯nder');
INSERT INTO Zip VALUES ('6280', 'H¯jer');
INSERT INTO Zip VALUES ('6300', 'GrÂsten');
INSERT INTO Zip VALUES ('6310', 'Broager');
INSERT INTO Zip VALUES ('6320', 'Egernsund');
INSERT INTO Zip VALUES ('6330', 'Padborg');
INSERT INTO Zip VALUES ('6340', 'KrusÂ');
INSERT INTO Zip VALUES ('6360', 'Tinglev');
INSERT INTO Zip VALUES ('6372', 'Bylderup-Bov');
INSERT INTO Zip VALUES ('6392', 'Bolderslev');
INSERT INTO Zip VALUES ('6400', 'S¯nderborg');
INSERT INTO Zip VALUES ('6430', 'Nordborg');
INSERT INTO Zip VALUES ('6440', 'Augustenborg');
INSERT INTO Zip VALUES ('6470', 'Sydals');
INSERT INTO Zip VALUES ('6500', 'Vojens');
INSERT INTO Zip VALUES ('6510', 'Gram');
INSERT INTO Zip VALUES ('6520', 'Toftlund');
INSERT INTO Zip VALUES ('6534', 'Agerskov');
INSERT INTO Zip VALUES ('6535', 'Branderup J');
INSERT INTO Zip VALUES ('6541', 'Bevtoft');
INSERT INTO Zip VALUES ('6560', 'Sommersted');
INSERT INTO Zip VALUES ('6580', 'Vamdrup');
INSERT INTO Zip VALUES ('6600', 'Vejen');
INSERT INTO Zip VALUES ('6621', 'Gesten');
INSERT INTO Zip VALUES ('6622', 'BÊkke');
INSERT INTO Zip VALUES ('6623', 'Vorbasse');
INSERT INTO Zip VALUES ('6630', 'R¯dding');
INSERT INTO Zip VALUES ('6640', 'Lunderskov');
INSERT INTO Zip VALUES ('6650', 'Br¯rup');
INSERT INTO Zip VALUES ('6660', 'Lintrup');
INSERT INTO Zip VALUES ('6670', 'Holsted');
INSERT INTO Zip VALUES ('6682', 'Hovborg');
INSERT INTO Zip VALUES ('6683', 'F¯vling');
INSERT INTO Zip VALUES ('6690', 'G¯rding');
INSERT INTO Zip VALUES ('6700', 'Esbjerg');
INSERT INTO Zip VALUES ('6701', 'Esbjerg');
INSERT INTO Zip VALUES ('6705', 'Esbjerg ÿ');
INSERT INTO Zip VALUES ('6710', 'Esbjerg V');
INSERT INTO Zip VALUES ('6715', 'Esbjerg N');
INSERT INTO Zip VALUES ('6720', 'Fan¯');
INSERT INTO Zip VALUES ('6731', 'TjÊreborg');
INSERT INTO Zip VALUES ('6740', 'Bramming');
INSERT INTO Zip VALUES ('6752', 'Glejbjerg');
INSERT INTO Zip VALUES ('6753', 'AgerbÊk');
INSERT INTO Zip VALUES ('6760', 'Ribe');
INSERT INTO Zip VALUES ('6771', 'Gredstedbro');
INSERT INTO Zip VALUES ('6780', 'SkÊrbÊk');
INSERT INTO Zip VALUES ('6792', 'R¯m¯');
INSERT INTO Zip VALUES ('6800', 'Varde');
INSERT INTO Zip VALUES ('6818', '≈rre');
INSERT INTO Zip VALUES ('6823', 'Ansager');
INSERT INTO Zip VALUES ('6830', 'N¯rre Nebel');
INSERT INTO Zip VALUES ('6840', 'Oksb¯l');
INSERT INTO Zip VALUES ('6851', 'Janderup Vestj');
INSERT INTO Zip VALUES ('6852', 'Billum');
INSERT INTO Zip VALUES ('6853', 'Vejers Strand');
INSERT INTO Zip VALUES ('6854', 'Henne');
INSERT INTO Zip VALUES ('6855', 'Outrup');
INSERT INTO Zip VALUES ('6857', 'BlÂvand');
INSERT INTO Zip VALUES ('6862', 'Tistrup');
INSERT INTO Zip VALUES ('6870', 'ÿlgod');
INSERT INTO Zip VALUES ('6880', 'Tarm');
INSERT INTO Zip VALUES ('6893', 'Hemmet');
INSERT INTO Zip VALUES ('6900', 'Skjern');
INSERT INTO Zip VALUES ('6920', 'VidebÊk');
INSERT INTO Zip VALUES ('6933', 'KibÊk');
INSERT INTO Zip VALUES ('6940', 'Lem St');
INSERT INTO Zip VALUES ('6950', 'Ringk¯bing');
INSERT INTO Zip VALUES ('6960', 'Hvide Sande');
INSERT INTO Zip VALUES ('6971', 'Spjald');
INSERT INTO Zip VALUES ('6973', 'ÿrnh¯j');
INSERT INTO Zip VALUES ('6980', 'Tim');
INSERT INTO Zip VALUES ('6990', 'Ulfborg');
INSERT INTO Zip VALUES ('7000', 'Fredericia');
INSERT INTO Zip VALUES ('7007', 'Fredericia');
INSERT INTO Zip VALUES ('7029', 'Fredericia');
INSERT INTO Zip VALUES ('7080', 'B¯rkop');
INSERT INTO Zip VALUES ('7100', 'Vejle');
INSERT INTO Zip VALUES ('7120', 'Vejle ÿst');
INSERT INTO Zip VALUES ('7130', 'Juelsminde');
INSERT INTO Zip VALUES ('7140', 'Stouby');
INSERT INTO Zip VALUES ('7150', 'Barrit');
INSERT INTO Zip VALUES ('7160', 'T¯rring');
INSERT INTO Zip VALUES ('7171', 'Uldum');
INSERT INTO Zip VALUES ('7173', 'Vonge');
INSERT INTO Zip VALUES ('7182', 'Bredsten');
INSERT INTO Zip VALUES ('7183', 'Randb¯l');
INSERT INTO Zip VALUES ('7184', 'Vandel');
INSERT INTO Zip VALUES ('7190', 'Billund');
INSERT INTO Zip VALUES ('7200', 'Grindsted');
INSERT INTO Zip VALUES ('7250', 'Hejnsvig');
INSERT INTO Zip VALUES ('7260', 'S¯nder Omme');
INSERT INTO Zip VALUES ('7270', 'Stakroge');
INSERT INTO Zip VALUES ('7280', 'S¯nder Felding');
INSERT INTO Zip VALUES ('7300', 'Jelling');
INSERT INTO Zip VALUES ('7321', 'Gadbjerg');
INSERT INTO Zip VALUES ('7323', 'Give');
INSERT INTO Zip VALUES ('7330', 'Brande');
INSERT INTO Zip VALUES ('7361', 'Ejstrupholm');
INSERT INTO Zip VALUES ('7362', 'Hampen');
INSERT INTO Zip VALUES ('7400', 'Herning');
INSERT INTO Zip VALUES ('7401', 'Herning');
INSERT INTO Zip VALUES ('7429', 'Herning');
INSERT INTO Zip VALUES ('7430', 'Ikast');
INSERT INTO Zip VALUES ('7441', 'Bording');
INSERT INTO Zip VALUES ('7442', 'Engesvang');
INSERT INTO Zip VALUES ('7451', 'Sunds');
INSERT INTO Zip VALUES ('7470', 'Karup J');
INSERT INTO Zip VALUES ('7480', 'Vildbjerg');
INSERT INTO Zip VALUES ('7490', 'Aulum');
INSERT INTO Zip VALUES ('7500', 'Holstebro');
INSERT INTO Zip VALUES ('7540', 'Haderup');
INSERT INTO Zip VALUES ('7550', 'S¯rvad');
INSERT INTO Zip VALUES ('7560', 'Hjerm');
INSERT INTO Zip VALUES ('7570', 'Vemb');
INSERT INTO Zip VALUES ('7600', 'Struer');
INSERT INTO Zip VALUES ('7620', 'Lemvig');
INSERT INTO Zip VALUES ('7650', 'B¯vlingbjerg');
INSERT INTO Zip VALUES ('7660', 'BÊkmarksbro');
INSERT INTO Zip VALUES ('7673', 'Harbo¯re');
INSERT INTO Zip VALUES ('7680', 'Thybor¯n');
INSERT INTO Zip VALUES ('7700', 'Thisted');
INSERT INTO Zip VALUES ('7730', 'Hanstholm');
INSERT INTO Zip VALUES ('7741', 'Fr¯strup');
INSERT INTO Zip VALUES ('7742', 'Vesl¯s');
INSERT INTO Zip VALUES ('7752', 'Snedsted');
INSERT INTO Zip VALUES ('7755', 'Bedsted Thy');
INSERT INTO Zip VALUES ('7760', 'Hurup Thy');
INSERT INTO Zip VALUES ('7770', 'Vestervig');
INSERT INTO Zip VALUES ('7790', 'Thyholm');
INSERT INTO Zip VALUES ('7800', 'Skive');
INSERT INTO Zip VALUES ('7830', 'Vinderup');
INSERT INTO Zip VALUES ('7840', 'H¯jslev');
INSERT INTO Zip VALUES ('7850', 'Stoholm Jyll');
INSERT INTO Zip VALUES ('7860', 'Sp¯ttrup');
INSERT INTO Zip VALUES ('7870', 'Roslev');
INSERT INTO Zip VALUES ('7884', 'Fur');
INSERT INTO Zip VALUES ('7900', 'Nyk¯bing M');
INSERT INTO Zip VALUES ('7950', 'Erslev');
INSERT INTO Zip VALUES ('7960', 'Karby');
INSERT INTO Zip VALUES ('7970', 'Redsted M');
INSERT INTO Zip VALUES ('7980', 'Vils');
INSERT INTO Zip VALUES ('7990', 'ÿster Assels');
INSERT INTO Zip VALUES ('8000', '≈rhus C');
INSERT INTO Zip VALUES ('8011', '≈rhus C');
INSERT INTO Zip VALUES ('8100', '≈rhus C');
INSERT INTO Zip VALUES ('8200', '≈rhus N');
INSERT INTO Zip VALUES ('8210', '≈rhus V');
INSERT INTO Zip VALUES ('8220', 'Brabrand');
INSERT INTO Zip VALUES ('8229', 'Risskov ÿ');
INSERT INTO Zip VALUES ('8230', '≈byh¯j');
INSERT INTO Zip VALUES ('8240', 'Risskov');
INSERT INTO Zip VALUES ('8245', 'Risskov ÿ');
INSERT INTO Zip VALUES ('8250', 'EgÂ');
INSERT INTO Zip VALUES ('8260', 'Viby J');
INSERT INTO Zip VALUES ('8270', 'H¯jbjerg');
INSERT INTO Zip VALUES ('8300', 'Odder');
INSERT INTO Zip VALUES ('8305', 'Sams¯');
INSERT INTO Zip VALUES ('8310', 'Tranbjerg J');
INSERT INTO Zip VALUES ('8320', 'MÂrslet');
INSERT INTO Zip VALUES ('8330', 'Beder');
INSERT INTO Zip VALUES ('8340', 'Malling');
INSERT INTO Zip VALUES ('8350', 'Hundslund');
INSERT INTO Zip VALUES ('8355', 'Solbjerg');
INSERT INTO Zip VALUES ('8361', 'Hasselager');
INSERT INTO Zip VALUES ('8362', 'H¯rning');
INSERT INTO Zip VALUES ('8370', 'Hadsten');
INSERT INTO Zip VALUES ('8380', 'Trige');
INSERT INTO Zip VALUES ('8381', 'Tilst');
INSERT INTO Zip VALUES ('8382', 'Hinnerup');
INSERT INTO Zip VALUES ('8400', 'Ebeltoft');
INSERT INTO Zip VALUES ('8410', 'R¯nde');
INSERT INTO Zip VALUES ('8420', 'Knebel');
INSERT INTO Zip VALUES ('8444', 'Balle');
INSERT INTO Zip VALUES ('8450', 'Hammel');
INSERT INTO Zip VALUES ('8462', 'Harlev J');
INSERT INTO Zip VALUES ('8464', 'Galten');
INSERT INTO Zip VALUES ('8471', 'Sabro');
INSERT INTO Zip VALUES ('8472', 'Sporup');
INSERT INTO Zip VALUES ('8500', 'Grenaa');
INSERT INTO Zip VALUES ('8520', 'Lystrup');
INSERT INTO Zip VALUES ('8530', 'Hjortsh¯j');
INSERT INTO Zip VALUES ('8541', 'Sk¯dstrup');
INSERT INTO Zip VALUES ('8543', 'Hornslet');
INSERT INTO Zip VALUES ('8544', 'M¯rke');
INSERT INTO Zip VALUES ('8550', 'RyomgÂrd');
INSERT INTO Zip VALUES ('8560', 'Kolind');
INSERT INTO Zip VALUES ('8570', 'Trustrup');
INSERT INTO Zip VALUES ('8581', 'Nimtofte');
INSERT INTO Zip VALUES ('8585', 'Glesborg');
INSERT INTO Zip VALUES ('8586', 'ÿrum Djurs');
INSERT INTO Zip VALUES ('8592', 'Anholt');
INSERT INTO Zip VALUES ('8600', 'Silkeborg');
INSERT INTO Zip VALUES ('8620', 'Kjellerup');
INSERT INTO Zip VALUES ('8632', 'Lemming');
INSERT INTO Zip VALUES ('8641', 'Sorring');
INSERT INTO Zip VALUES ('8643', 'Ans By');
INSERT INTO Zip VALUES ('8653', 'Them');
INSERT INTO Zip VALUES ('8654', 'Bryrup');
INSERT INTO Zip VALUES ('8660', 'Skanderborg');
INSERT INTO Zip VALUES ('8670', 'LÂsby');
INSERT INTO Zip VALUES ('8680', 'Ry');
INSERT INTO Zip VALUES ('8700', 'Horsens');
INSERT INTO Zip VALUES ('8721', 'DaugÂrd');
INSERT INTO Zip VALUES ('8722', 'Hedensted');
INSERT INTO Zip VALUES ('8723', 'L¯sning');
INSERT INTO Zip VALUES ('8732', 'HovedgÂrd');
INSERT INTO Zip VALUES ('8740', 'BrÊdstrup');
INSERT INTO Zip VALUES ('8751', 'Gedved');
INSERT INTO Zip VALUES ('8752', 'ÿstbirk');
INSERT INTO Zip VALUES ('8762', 'Flemming');
INSERT INTO Zip VALUES ('8763', 'Rask M¯lle');
INSERT INTO Zip VALUES ('8765', 'Klovborg');
INSERT INTO Zip VALUES ('8766', 'N¯rre Snede');
INSERT INTO Zip VALUES ('8781', 'Stenderup');
INSERT INTO Zip VALUES ('8783', 'Hornsyld');
INSERT INTO Zip VALUES ('8800', 'Viborg');
INSERT INTO Zip VALUES ('8830', 'Tjele');
INSERT INTO Zip VALUES ('8831', 'L¯gstrup');
INSERT INTO Zip VALUES ('8832', 'Skals');
INSERT INTO Zip VALUES ('8840', 'R¯Êrsbro');
INSERT INTO Zip VALUES ('8850', 'Bjerringbro');
INSERT INTO Zip VALUES ('8860', 'Ulstrup');
INSERT INTO Zip VALUES ('8870', 'LangÂ');
INSERT INTO Zip VALUES ('8881', 'Thors¯');
INSERT INTO Zip VALUES ('8882', 'FÂrvang');
INSERT INTO Zip VALUES ('8883', 'Gjern');
INSERT INTO Zip VALUES ('8900', 'Randers C');
INSERT INTO Zip VALUES ('8920', 'Randers NV');
INSERT INTO Zip VALUES ('8930', 'Randers Nÿ');
INSERT INTO Zip VALUES ('8940', 'Randers SV');
INSERT INTO Zip VALUES ('8950', 'ÿrsted');
INSERT INTO Zip VALUES ('8960', 'Randers Sÿ');
INSERT INTO Zip VALUES ('8961', 'AllingÂbro');
INSERT INTO Zip VALUES ('8963', 'Auning');
INSERT INTO Zip VALUES ('8970', 'Havndal');
INSERT INTO Zip VALUES ('8981', 'Spentrup');
INSERT INTO Zip VALUES ('8983', 'Gjerlev J');
INSERT INTO Zip VALUES ('8990', 'FÂrup');
INSERT INTO Zip VALUES ('9000', 'Aalborg');
INSERT INTO Zip VALUES ('9020', 'Aalborg');
INSERT INTO Zip VALUES ('9029', 'Aalborg');
INSERT INTO Zip VALUES ('9100', 'Aalborg');
INSERT INTO Zip VALUES ('9200', 'Aalborg SV');
INSERT INTO Zip VALUES ('9210', 'Aalborg Sÿ');
INSERT INTO Zip VALUES ('9220', 'Aalborg ÿst');
INSERT INTO Zip VALUES ('9230', 'Svenstrup J');
INSERT INTO Zip VALUES ('9240', 'Nibe');
INSERT INTO Zip VALUES ('9260', 'Gistrup');
INSERT INTO Zip VALUES ('9270', 'Klarup');
INSERT INTO Zip VALUES ('9280', 'Storvorde');
INSERT INTO Zip VALUES ('9293', 'Kongerslev');
INSERT INTO Zip VALUES ('9300', 'SÊby');
INSERT INTO Zip VALUES ('9310', 'Vodskov');
INSERT INTO Zip VALUES ('9320', 'Hjallerup');
INSERT INTO Zip VALUES ('9330', 'Dronninglund');
INSERT INTO Zip VALUES ('9340', 'Asaa');
INSERT INTO Zip VALUES ('9352', 'Dybvad');
INSERT INTO Zip VALUES ('9362', 'Gandrup');
INSERT INTO Zip VALUES ('9370', 'Hals');
INSERT INTO Zip VALUES ('9380', 'Vestbjerg');
INSERT INTO Zip VALUES ('9381', 'Sulsted');
INSERT INTO Zip VALUES ('9382', 'Tylstrup');
INSERT INTO Zip VALUES ('9400', 'N¯rresundby');
INSERT INTO Zip VALUES ('9430', 'Vadum');
INSERT INTO Zip VALUES ('9440', 'Aabybro');
INSERT INTO Zip VALUES ('9460', 'Brovst');
INSERT INTO Zip VALUES ('9480', 'L¯kken');
INSERT INTO Zip VALUES ('9490', 'Pandrup');
INSERT INTO Zip VALUES ('9492', 'Blokhus');
INSERT INTO Zip VALUES ('9493', 'Saltum');
INSERT INTO Zip VALUES ('9500', 'Hobro');
INSERT INTO Zip VALUES ('9510', 'Arden');
INSERT INTO Zip VALUES ('9520', 'Sk¯rping');
INSERT INTO Zip VALUES ('9530', 'St¯vring');
INSERT INTO Zip VALUES ('9541', 'Suldrup');
INSERT INTO Zip VALUES ('9550', 'Mariager');
INSERT INTO Zip VALUES ('9560', 'Hadsund');
INSERT INTO Zip VALUES ('9574', 'BÊlum');
INSERT INTO Zip VALUES ('9575', 'Terndrup');
INSERT INTO Zip VALUES ('9600', 'Aars');
INSERT INTO Zip VALUES ('9610', 'N¯rager');
INSERT INTO Zip VALUES ('9620', 'Aalestrup');
INSERT INTO Zip VALUES ('9631', 'Gedsted');
INSERT INTO Zip VALUES ('9632', 'M¯ldrup');
INSERT INTO Zip VALUES ('9640', 'Fars¯');
INSERT INTO Zip VALUES ('9670', 'L¯gst¯r');
INSERT INTO Zip VALUES ('9681', 'Ranum');
INSERT INTO Zip VALUES ('9690', 'Fjerritslev');
INSERT INTO Zip VALUES ('9700', 'Br¯nderslev');
INSERT INTO Zip VALUES ('9740', 'Jerslev J');
INSERT INTO Zip VALUES ('9750', 'ÿstervrÂ');
INSERT INTO Zip VALUES ('9760', 'VrÂ');
INSERT INTO Zip VALUES ('9800', 'Hj¯rring');
INSERT INTO Zip VALUES ('9830', 'TÂrs');
INSERT INTO Zip VALUES ('9850', 'Hirtshals');
INSERT INTO Zip VALUES ('9870', 'Sindal');
INSERT INTO Zip VALUES ('9881', 'Bindslev');
INSERT INTO Zip VALUES ('9900', 'Frederikshavn');
INSERT INTO Zip VALUES ('9940', 'LÊs¯');
INSERT INTO Zip VALUES ('9970', 'Strandby');
INSERT INTO Zip VALUES ('9981', 'Jerup');
INSERT INTO Zip VALUES ('9982', '≈lbÊk');
INSERT INTO Zip VALUES ('9990', 'Skagen');

INSERT INTO login (username, password, user_role, user_firm) 
VALUES ('Oliver', '123', 'admin', 'Polygon1');
INSERT INTO login (username, password, user_role, user_firm) 
VALUES ('Tim', '1234', 'admin', 'Polygon');
INSERT INTO login (username, password, user_role, user_firm) 
VALUES ('Phillip', '12345', 'customer', 'ABE');
INSERT INTO login (username, password, user_role, user_firm) 
VALUES ('Michael', '123456', 'admin', 'Polygon2');
INSERT INTO login (username, password, user_role, user_firm) 
VALUES ('Brink', '123', 'customer', 'PC');

INSERT INTO firm (firm_name, firm_leader_id) VALUES ('Polygon1', 1);
INSERT INTO firm (firm_name, firm_leader_id) VALUES ('Polygon', 2);
INSERT INTO firm (firm_name, firm_leader_id) VALUES ('ABE', 3);
INSERT INTO firm (firm_name, firm_leader_id) VALUES ('Polygon2', 4);
INSERT INTO firm (firm_name, firm_leader_id) VALUES ('PC', 5);

INSERT INTO buildings (building_name, building_status, building_type, building_adress, building_year, building_zipcode, building_areasize, building_parcel_no, building_floor, building_firm_id)
VALUES ('Olivers bygning', 'I stand', 'Hus', 'Kappa 123', 1992, 1000, 70, '123', '1', 1);
INSERT INTO buildings (building_name, building_status, building_type, building_adress, building_year, building_zipcode, building_areasize, building_parcel_no, building_floor, building_firm_id) 
VALUES ('Olivers bygning', 'I stand', 'Hus', 'Kappa 123', 1992, 2000, 70, '123', '1', 1);
INSERT INTO buildings (building_name, building_status, building_type, building_adress, building_year, building_zipcode, building_areasize, building_parcel_no, building_floor, building_firm_id) 
VALUES ('Olivers bygning', 'I stand', 'Hus', 'Kappa 123', 1992, 3000, 70, '123', '1', 2);
INSERT INTO buildings (building_name, building_status, building_type, building_adress, building_year, building_zipcode, building_areasize, building_parcel_no, building_floor, building_firm_id) 
VALUES ('Olivers bygning', 'I stand', 'Hus', 'Kappa 123', 1992, 4000, 70, '123', '1', 2);
INSERT INTO buildings (building_name, building_status, building_type, building_adress, building_year, building_zipcode, building_areasize, building_parcel_no, building_floor, building_firm_id) 
VALUES ('Olivers bygning', 'I stand', 'Hus', 'Kappa 123', 1992, 5000, 70, '123', '1', 3);
INSERT INTO buildings (building_name, building_status, building_type, building_adress, building_year, building_zipcode, building_areasize, building_parcel_no, building_floor, building_firm_id)
VALUES ('Olivers bygning', 'I stand', 'Hus', 'Kappa 123', 1992, 6000, 70, '123', '1', 3);
INSERT INTO buildings (building_name, building_status, building_type, building_adress, building_year, building_zipcode, building_areasize, building_parcel_no, building_floor, building_firm_id)
VALUES ('Olivers bygning', 'I stand', 'Hus', 'Kappa 123', 1992, 7000, 70, '123', '1', 4);
INSERT INTO buildings (building_name, building_status, building_type, building_adress, building_year, building_zipcode, building_areasize, building_parcel_no, building_floor, building_firm_id) 
VALUES ('Olivers bygning', 'I stand', 'Hus', 'Kappa 123', 1992, 8000, 70, '123', '1', 4);
INSERT INTO buildings (building_name, building_status, building_type, building_adress, building_year, building_zipcode, building_areasize, building_parcel_no, building_floor, building_firm_id) 
VALUES ('Olivers bygning', 'I stand', 'Hus', 'Kappa 123', 1992, 9000, 70, '123', '1', 4);

INSERT INTO building_report (report_id, report_outer_roof, report_outer_wall, report_building_usage, report_building_manager, report_building_condetion)
VALUES (1, 'Good', 'Medium', 'Shallo', 'Poly', 2);

select * from building_report;

/*
SELECT * FROM building_floors;
DELETE FROM building_floors WHERE floor_building_id = 10;

SELECT building_floors.floor_no, building_floors.floor_size, building_floors.floor_arpartments, building_floors.floor_rooms  from building_floors inner join buildings ON building_floors.floor_building_id = buildings.building_id WHERE building_id = 1;

select buildings.building_id, buildings.building_status, buildings.building_type, buildings.building_year, buildings.building_areasize, buildings.building_name, buildings.building_adress, buildings.building_floor, buildings.building_zipcode, firm.firm_name FROM buildings INNER JOIN firm ON buildings.building_firm_id = firm.firm_id Where building_firm_id = 1 ;

SELECT firm.firm_id FROM firm INNER JOIN login ON login.user_id = firm.firm_leader_id WHERE login.user_id = 2;

Select * from login;
select * from firm;
select * from images;

select * from login where username='Tim' and password ='1234';

UPDATE building_floors set floor_size = 300, floor_arpartments = '4', floor_rooms = '6' WHERE floor_no = 1 and floor_building_id = 1;

SELECT floor_size, floor_arpartments, floor_rooms from building_floors WHERE floor_no = 1 and floor_building_id = 1;

select * from buildings;
SELECT user_id FROM login WHERE username = 'Martin' and password = '123';
select buildings.building_id, buildings.building_status, buildings.building_type, buildings.building_year, buildings.building_areasize, buildings.building_name, buildings.building_adress, buildings.building_floor, buildings.building_zipcode, firm.firm_name FROM buildings INNER JOIN firm ON buildings.building_firm_id = firm.firm_id;
*/